# Generated by Django 4.2.3 on 2023-07-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('description', models.TextField(max_length=1500)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('fb_link', models.URLField(max_length=500)),
                ('x_link', models.URLField(max_length=500)),
                ('insta_link', models.URLField(max_length=500)),
            ],
        ),
    ]
